export default [
  {
    date: new Date(2024, 9),
    label: "Principal Engineer",
    tooltip: "Atom Bank",
    tenure: "Current",
    tech: ["Go", "GCP", "k8s"],
    highlights: [
      "Leading the Lending Value Stream",
      "Led the migration to a new decisioning tool",
      "Led the migration to a new servicing platform",
      "Led the implementation of Basel 3.1 migration",
    ],
  },
  {
    date: new Date(2023, 0),
    label: "Senior Software Engineer",
    tooltip: "Bloom",
    tenure: "1 year 9 months",
    tech: ["Node.js", "AWS", "Serverless"],
    highlights: [
      "Built user identity service as the backbone of the product",
      "Implemented data architecture using AWS and GCP including ETL pipelines and dashboarding",
      "Scaled testing automation strategy across a microservice architecture",
      "Did a lot of other things...",
    ],
  },
  {
    date: new Date(2022, 7),
    label: "Senior Software Engineer",
    tenure: "5 months",
    tooltip: "Infogrid",
    tech: ["Python", "React"],
    highlights: [
      "Ran event storming and user story workshops",
      "Picked up enterprise-level Python within two months",
      "Delivered frontend features during colleague absences",
    ],
  },
  {
    date: new Date(2022, 1),
    label: "Senior Software Engineer",
    tenure: "7 months",
    tooltip: "Cazoo",
    tech: ["Node.js", "React"],
    highlights: [
      "Reduced integration test runtime by 75%",
      "Implemented features enabling Cazoo's European rollout",
    ],
  },
  {
    date: new Date(2021, 9),
    label: "Senior Full Stack Engineer",
    tooltip: "Reach PLC",
    tenure: "1 year 5 months",
    tech: ["Node.js", "React", "TypeScript", "AWS CDK"],
    highlights: [
      "Scaled a newsletter subscription service to 2 million users",
      "Led CICD pipeline implementation via CDK and CodePipeline",
      "Built the user platform for memorylane.co.uk",
    ],
  },
  {
    date: new Date(2020, 9),
    label: "Full Stack Engineer",
    tooltip: "Reach PLC",
    tech: ["Node.js", "React"],
    highlights: [],
  },
  {
    date: new Date(2019, 6),
    label: "Solutions Engineer",
    tooltip: "Tray.io",
    tenure: "1 year 4 months",
    tech: ["Node.js", "AWS Lambda"],
    highlights: [
      "Built a testing library on top of Nock and Jest for junior engineers",
      "Developed lambda connectors integrating with 3rd party APIs",
      "Built an automated release notes system for Tray.io connectors",
    ],
  },
  {
    date: new Date(2018, 8),
    label: "SDE II",
    tooltip: "Tesco PLC",
    tenure: "1 year 10 months",
    tech: ["Node.js"],
    highlights: [
      "Promoted to SDE II after 1 year on the graduate scheme",
      "Led development of a new till printing service",
      "3-month placement in India",
    ],
  },
  {
    date: new Date(2017, 8),
    label: "Graduate Software Engineer",
    tooltip: "Tesco PLC",
    tech: ["Node.js"],
    highlights: [],
  },
  {
    date: new Date(2017, 6),
    label: "Computer Science Graduate",
    tooltip: "University of Sheffield",
    tech: [],
    highlights: ["Graduated with a 1st class degree in Computer Science"],
  },
  {
    date: new Date(2016, 6),
    label: "Technology Intern",
    tenure: "3 months",
    tooltip: "Tesco PLC Intern",
    tech: [],
    highlights: ["Built a secret scanning tool for Tesco's internal GitHub"],
  },
  {
    date: new Date(2015, 6),
    label: "Engineering Intern",
    tenure: "3 months",
    tooltip: "BT",
    tech: [],
    highlights: [
      "Built Apple Watch apps showcasing how wearables could be used to exploit security systems",
    ],
  },
  {
    date: new Date(2013, 8),
    label: "Student",
    tenure: "4 years",
    tooltip: "University of Sheffield",
    tech: [],
    highlights: ["Achieved 1st class degree MComp Computer Science"],
  },
];
